### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by davidagold** [davidagold/zhum#9]
List of features to implement, guided largely by https://ggplot2.tidyverse.org/reference/. 

Geometries
- [ ] `point` https://github.com/davidagold/zhum/issues/6
- [ ] `bar` https://github.com/davidagold/zhum/issues/7
- [ ] `col` https://github.com/davidagold/zhum/issues/8

Guides
- [ ] axes
- [ ] legends
